#! /Users/mohitjandwani/anaconda3/bin/python
import os
import click

@click.command()
@click.option('--tmux',default=1,help='use tmux')
@click.option('--ts', default='def', help='tmux session name')
@click.option('--vpc', default='app', help='vpc user or app')
def sjp(tmux,ts,vpc):
    ip = '54.209.38.182' if vpc == 'app' else '54.87.137.227'
    if tmux:
        cmd = 'ssh -t mohitkumar@{0} tmux attach -t {1}'.format(ip,ts)
    else:
        cmd = 'ssh mohitkumar@{}'.format(ip)
    os.system(cmd)

@click.command()
@click.option('-s',help='server name')
@click.option('--vpc',default='app',help='vpc of server')
def goto(s,vpc):
    dns = s + '.sntio.com'
    ip = '54.209.38.182' if vpc == 'app' else '54.87.137.227'
    cmd = 'ssh -t mohitkumar@{0} ssh {1}'.format(ip,dns)
    os.system(cmd)

@click.group()
def main():
    pass

main.add_command(sjp)
main.add_command(goto)

if __name__ == "__main__":
    main()
